### ISSUE TITLE
Crash during register when the BLUETOOTH permission is missing

### ISSUE THREAD

**Issue by mickael-menu** [readium/r2-lcp-kotlin#66]
It looks like the generation of the device UUID requires the BLUETOOTH permission to be enabled in the app, otherwise the `register` operation will fail.

This permission is not set in the test app, so we get the following exception. But maybe there are ways to generate a device UUID which doesn't require an additional permission. Any ideas?

https://github.com/readium/r2-lcp-kotlin/blob/995584bb8dbb0eb9fcc661c6930838f12af1adc2/r2-lcp/src/main/java/org/readium/r2/lcp/service/DeviceService.kt#L32-L40

```
E/LicenseValidation: java.lang.SecurityException: Need BLUETOOTH permission: Neither user 10286 nor current process has android.permission.BLUETOOTH.
E/LicenseValidation:     at android.os.Parcel.createException(Parcel.java:2071)
E/LicenseValidation:     at android.os.Parcel.readException(Parcel.java:2039)
E/LicenseValidation:     at android.os.Parcel.readException(Parcel.java:1987)
E/LicenseValidation:     at android.bluetooth.IBluetoothManager$Stub$Proxy.getName(IBluetoothManager.java:680)
E/LicenseValidation:     at android.bluetooth.BluetoothAdapter.getName(BluetoothAdapter.java:1178)
E/LicenseValidation:     at org.readium.r2.lcp.service.DeviceService.getName(DeviceService.kt:35)
E/LicenseValidation:     at org.readium.r2.lcp.service.DeviceService.getAsQueryParameters(DeviceService.kt:43)
E/LicenseValidation:     at org.readium.r2.lcp.service.DeviceService$registerLicense$1.invokeSuspend(DeviceService.kt:53)
E/LicenseValidation:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/LicenseValidation:     at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
E/LicenseValidation:     at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
E/LicenseValidation:     at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:80)
E/LicenseValidation:     at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
E/LicenseValidation:     at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
E/LicenseValidation:     at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
E/LicenseValidation:     at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
E/LicenseValidation:     at org.readium.r2.lcp.service.DeviceService.registerLicense(DeviceService.kt:47)
E/LicenseValidation:     at org.readium.r2.lcp.license.LicenseValidation.registerDevice(LicenseValidation.kt:382)
E/LicenseValidation:     at org.readium.r2.lcp.license.LicenseValidation.handle(LicenseValidation.kt:274)
E/LicenseValidation:     at org.readium.r2.lcp.license.LicenseValidation.setState(LicenseValidation.kt:96)
E/LicenseValidation:     at org.readium.r2.lcp.license.LicenseValidation$stateMachine$1$12.invoke(LicenseValidation.kt:254)
E/LicenseValidation:     at org.readium.r2.lcp.license.LicenseValidation$stateMachine$1$12.invoke(LicenseValidation.kt:83)
E/LicenseValidation:     at org.readium.r2.lcp.license.StateMachine.notifyOnTransition(StateMachine.kt:75)
E/LicenseValidation:     at org.readium.r2.lcp.license.StateMachine.transition(StateMachine.kt:32)
E/LicenseValidation:     at org.readium.r2.lcp.license.LicenseValidation.raise(LicenseValidation.kt:260)
E/LicenseValidation:     at org.readium.r2.lcp.license.LicenseValidation.access$raise(LicenseValidation.kt:83)
E/LicenseValidation:     at org.readium.r2.lcp.license.LicenseValidation$validateIntegrity$1.invoke(LicenseValidation.kt:376)
E/LicenseValidation:     at org.readium.r2.lcp.license.LicenseValidation$validateIntegrity$1.invoke(LicenseValidation.kt:83)
E/LicenseValidation:     at org.readium.r2.lcp.service.CRLService.retrieve(CRLService.kt:37)
E/LicenseValidation:     at org.readium.r2.lcp.license.LicenseValidation.validateIntegrity(LicenseValidation.kt:374)
E/LicenseValidation:     at org.readium.r2.lcp.license.LicenseValidation.handle(LicenseValidation.kt:273)
E/LicenseValidation:     at org.readium.r2.lcp.license.LicenseValidation.setState(LicenseValidation.kt:96)
E/LicenseValidation:     at org.readium.r2.lcp.license.LicenseValidation$stateMachine$1$12.invoke(LicenseValidation.kt:254)
E/LicenseValidation:     at org.readium.r2.lcp.license.LicenseValidation$stateMachine$1$12.invoke(LicenseValidation.kt:83)
E/LicenseValidation:     at org.readium.r2.lcp.license.StateMachine.notifyOnTransition(StateMachine.kt:75)
E/LicenseValidation:     at org.readium.r2.lcp.license.StateMachine.transition(StateMachine.kt:32)
E/LicenseValidation:     at org.readium.r2.lcp.license.LicenseValidation.raise(LicenseValidation.kt:260)
E/LicenseValidation:     at org.readium.r2.lcp.license.LicenseValidation.access$raise(LicenseValidation.kt:83)
E/LicenseValidation:     at org.readium.r2.lcp.license.LicenseValidation$requestPassphrase$1.invoke(LicenseValidation.kt:361)
E/LicenseValidation:     at org.readium.r2.lcp.license.LicenseValidation$requestPassphrase$1.invoke(LicenseValidation.kt:83)
E/LicenseValidation:     at org.readium.r2.lcp.service.PassphrasesService$request$1.invokeSuspend(PassphrasesService.kt:31)
```

**Comment by mickael-menu** [comment]
Actually it's not for the UUID but the name, so it's fine if it fails and we get "Unknown Android" instead. I'll just wrap the call in a `try` to make sure it doesn't crash.
